/**
 * طبقة توافق: نفس أسماء أيقونات lucide، لكن بأيقونات "كتبي" الخاصة بأسلوب Clash.
 * تسمح باستبدال الاستيراد في كل الموقع دون تغيير أماكن الاستخدام.
 */
import {
  IconSearch, IconMenu, IconHome, IconBell, IconMail, IconHeart, IconTrophy,
  IconGear, IconChat, IconBookOpen, IconShield, IconUser, IconUsers, IconCrown,
  IconCheck, IconCheckCircle, IconX, IconXCircle, IconAlert, IconInfoCircle,
  IconPlus, IconTrash, IconEdit, IconEye, IconEyeOff, IconDownload, IconUpload,
  IconSend, IconShare, IconCopy, IconRefresh, IconExternal, IconLock, IconClock,
  IconCalendar, IconFileText, IconGlobe, IconTrendingUp, IconStar, IconQuote,
  IconSparkles, IconFlame, IconCoins, IconGift, IconAward, IconMegaphone,
  IconImage, IconPalette, IconPlay, IconPause, IconChevronLeft, IconChevronRight,
  IconBot, IconLoader, IconArrowLeft, IconArrowRight, IconChevronDown, IconChevronUp,
  IconUserPlus, IconUserMinus, IconUserX, IconUserCheck, IconRotateCcw, IconSquare,
  IconCheckSquare, IconZoomIn, IconZoomOut, IconSun, IconMoon, IconMaximize, IconLink,
  IconLightbulb, IconLibrary, IconLayers, IconBarChart, IconZap, IconSave, IconLogOut,
  IconLogIn, IconMoreVertical, IconBookmark, IconMedal, IconCamera, IconHelp,
  IconShieldCheck, IconPlayCircle, IconVolume, IconVolumeOff, IconMic, IconTarget,
  IconThumbUp, IconThumbDown, IconSmile, IconShoppingBag, IconBuilding, IconPuzzle,
  IconVideo, IconWand,
} from './KotobiIcons';

export {
  IconSearch as Search,
  IconMenu as Menu,
  IconHome as Home,
  IconBell as Bell,
  IconMail as Mail,
  IconHeart as Heart,
  IconTrophy as Trophy,
  IconGear as Settings,
  IconChat as MessageSquare,
  IconChat as MessageCircle,
  IconBookOpen as BookOpen,
  IconShield as Shield,
  IconUser as User,
  IconUsers as Users,
  IconCrown as Crown,
  IconCheck as Check,
  IconCheckCircle as CheckCircle,
  IconCheckCircle as CheckCircle2,
  IconX as X,
  IconXCircle as XCircle,
  IconAlert as AlertTriangle,
  IconInfoCircle as AlertCircle,
  IconInfoCircle as Info,
  IconPlus as Plus,
  IconTrash as Trash2,
  IconEdit as Edit,
  IconEdit as Edit2,
  IconEdit as Edit3,
  IconEdit as Pencil,
  IconEye as Eye,
  IconEyeOff as EyeOff,
  IconDownload as Download,
  IconUpload as Upload,
  IconSend as Send,
  IconShare as Share2,
  IconCopy as Copy,
  IconRefresh as RefreshCw,
  IconExternal as ExternalLink,
  IconLock as Lock,
  IconClock as Clock,
  IconCalendar as Calendar,
  IconFileText as FileText,
  IconGlobe as Globe,
  IconTrendingUp as TrendingUp,
  IconStar as Star,
  IconQuote as Quote,
  IconSparkles as Sparkles,
  IconFlame as Flame,
  IconCoins as Coins,
  IconGift as Gift,
  IconAward as Award,
  IconMegaphone as Megaphone,
  IconImage as Image,
  IconPalette as Palette,
  IconPlay as Play,
  IconPause as Pause,
  IconChevronLeft as ChevronLeft,
  IconChevronRight as ChevronRight,
  IconBot as Bot,
  IconLoader as Loader2,
  IconLoader as LoaderCircle,
  IconLoader as Loader,
  IconArrowLeft as ArrowLeft,
  IconArrowRight as ArrowRight,
  IconChevronDown as ChevronDown,
  IconChevronUp as ChevronUp,
  IconUserPlus as UserPlus,
  IconUserMinus as UserMinus,
  IconUserX as UserX,
  IconUserCheck as UserCheck,
  IconRotateCcw as RotateCcw,
  IconSquare as Square,
  IconCheckSquare as CheckSquare,
  IconZoomIn as ZoomIn,
  IconZoomOut as ZoomOut,
  IconSun as Sun,
  IconMoon as Moon,
  IconMaximize as Maximize,
  IconLink as Link2,
  IconLink as LinkIcon,
  IconLightbulb as Lightbulb,
  IconLibrary as Library,
  IconLayers as Layers,
  IconBarChart as BarChart3,
  IconZap as Zap,
  IconSave as Save,
  IconLogOut as LogOut,
  IconLogIn as LogIn,
  IconMoreVertical as MoreVertical,
  IconBookmark as Bookmark,
  IconMedal as Medal,
  IconCamera as Camera,
  IconHelp as HelpCircle,
  IconShieldCheck as ShieldCheck,
  IconShieldCheck as BadgeCheck,
  IconPlayCircle as PlayCircle,
  IconVolume as Volume2,
  IconVolumeOff as VolumeX,
  IconMic as Mic,
  IconTarget as Target,
  IconThumbUp as ThumbsUp,
  IconThumbDown as ThumbsDown,
  IconSmile as Smile,
  IconSmile as SmilePlus,
  IconShoppingBag as ShoppingBag,
  IconBuilding as Building,
  IconPuzzle as Puzzle,
  IconVideo as Video,
  IconWand as Wand2,
  IconImage as ImageIcon,
};
